### PR TITLE
integrate codeql with tests

### PR DESCRIPTION
**Pull request by janisz**
As codeql build code there is no point in doint it twice. 
This PR integrates codeql scan with test workflow.

### CODE REVIEW

**Comment by janisz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #236** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/236" target="_blank">Graphite</a> 
    * **PR #235** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/235" target="_blank">Graphite</a> 
      * **PR #237** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/237" target="_blank">Graphite</a> 
        * **PR #240** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/240" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/240?utm_source=stack-comment).

**Review by dhaus67 — APPROVED** [review]

**Comment by janisz** [comment]
@janisz queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/240).

**Comment by janisz** [comment]
@janisz merged this pull request with [Graphite](https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/240).

**Comment by janisz** [comment]
[Graphite](https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/240) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Pull request merged**
