### PR TITLE
Migrate from dockerhub to quay

### PR DESCRIPTION
**Pull request by janisz**
> The best defense against the Docker Hub rate limiting is to move any base images needed to quay.io directly. Quay.io does not restrict the number of public repositories for any user (either free or paid). In addition, quay.io does not restrict anonymous pulls against its repositories (either public or private) and only rate limits in the most severe circumstances to maintain service levels (e.g. tens of requests per second from the same IP address).

https://access.redhat.com/articles/5531191

### CODE REVIEW

**Review by dhaus67 — APPROVED** [review]

**Comment by janisz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #236** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/236" target="_blank">Graphite</a>  👈
    * **PR #235** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/235" target="_blank">Graphite</a> 
      * **PR #237** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/237" target="_blank">Graphite</a> 
        * **PR #240** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/240" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/236?utm_source=stack-comment).

**Comment by janisz** [comment]
@janisz queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/236).

**Comment by janisz** [comment]
@janisz merged this pull request with [Graphite](https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/236).

**Comment by janisz** [comment]
[Graphite](https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/236) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Pull request merged**
