### PR TITLE
Bump junit-bom from 5.8.2 to 5.9.0 in /stackrox-container-image-scanner

### PR DESCRIPTION
**Pull request by janisz**

### CODE REVIEW

**Comment by janisz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #176** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/176" target="_blank">Graphite</a> 
    * **PR #165** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/165" target="_blank">Graphite</a> 
      * **PR #177** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/177" target="_blank">Graphite</a> 
        * **PR #164** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/164" target="_blank">Graphite</a> 
          * **PR #178** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/178" target="_blank">Graphite</a>  👈
          * **PR #168** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/168" target="_blank">Graphite</a> 
            * **PR #175** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/175" target="_blank">Graphite</a> 
              * **PR #172** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/172" target="_blank">Graphite</a> 
                * **PR #170** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/170" target="_blank">Graphite</a> 
      * **PR #167** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/167" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/178?utm_source=stack-comment).

**Review by dhaus67 — APPROVED** [review]

**Comment by janisz** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/178?utm_source=stack-comment).


Job Reference: k1TsZxd9Ccz9YmPqRkDw

**Comment by janisz** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/178?utm_source=stack-comment).


Job Reference: kZf9XRqdqG9eC6V9x71x

**Comment by janisz** [comment]
@dependabot recreate

**Comment by janisz** [comment]
@dependabot recreate

**Pull request closed without merging**
