### PR TITLE
Remove custom proxy

### PR DESCRIPTION
**Pull request by janisz**
Refs:

- https://github.com/stackrox/stackrox/pull/5348

### CODE REVIEW

**Comment by janisz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #236** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/236" target="_blank">Graphite</a> 
    * **PR #235** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/235" target="_blank">Graphite</a>  👈
      * **PR #237** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/237" target="_blank">Graphite</a> 
        * **PR #240** <a href="https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/240" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/235?utm_source=stack-comment).

**Review by dhaus67 — APPROVED** [review]

**Comment by janisz** [comment]
@janisz queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/235).

**Comment by janisz** [comment]
@janisz merged this pull request with [Graphite](https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/235).

**Comment by janisz** [comment]
[Graphite](https://app.graphite.dev/github/pr/stackrox/jenkins-plugin/235) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Pull request merged**
